name: '415 Tester CI'
run-name: ${{ github.actor }}
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: tests/run_tests.sh
