name: '415 Tester CI'
run-name: ${{ github.actor }}
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build tester
        run: mkdir build\ 
          && cd build\
          && cmake ..\
          && make 

      - name: run tests
        run: tests/run_tests.sh
